module ListOfFemaleShortNames
    $female_short = [
    "JO", "AJA", "EVE", "GIA", "LEY", "LUZ", "TIA", "AKWE", "AMIA", "ASIA", "CIJI", "DAJA", "DEJA", "DORA", "ERIN", "ESNA", "ISHA", "ISIS", "JADA", "JADE", "JAEL", "JAIA", "JANA", "JENE", "JINA", "LEIA", "LYNN", "MARY", "NINA", "NORA", "RUTH", "SADE", "SARA", "TEJA", "TONI", "TORI", "TYRA", "A'SJA", "AISSA", "ALINA", "AMARI", "AMIYA", "ANAYA", "ANGEL", "ANIAH", "ANIYA", "ARIEL", "ASHER", "ASHIA", "ATIRA", "AYANA", "BETSY", "BETTY", "BRINE","CACHE", "CARLA", "CIARA", "CIARI", "CINDY", "DAIJA", "DARLA", "DAZHA", "DEJAH", "DIEJA", "DIMOR", "DONNA", "DORIS", "EBONY", "EMILY", "ERICA", "ERIKA", "EVITA", "GEIDY", "HEIDY", "HILDA", "IBETH", "INDYA", "IRENA", "J'NYA", "JAMIA", "JANAE", "JANET", "JANYA", "JAVON", "JAYLA", "JENNY", "JOANA", "KAJAH", "KAREN", "KAYLA", "KAYRA", "KELIS", "KENYA", "KEONA", "KEORA", "KEREN", "KIANA", "KIARA", "KYARA", "KYSIA", "LAUDZ", "LAURA", "LEANN", "LEXIS", "LINDA", "LUARA", "LYRIC", "MAIYA", "MAKYA", "MARIE", "MONAY", "MYKIA", "N'DIA", "NADIA", "NAOMI", "NAYAH", "NYLAH", "PARIS", "QUEEN", "RANDI", "RAVEN", "ROBYN", "SAIRA", "SANIA", "SARAH", "TADZA", "TAMEA", "TAMIA", "TANIA", "TEHYA", "TERRI", "TIARA", "ULANI", "VASTY", "VICKY", "WINNY", "YOLNA", "ZARIA", "ZHANE", "ZOLAH"
    ]

  $female_short_strong = [
      "EVE", "TIA", "AMIA", "ASIA", "DAJA", "DEJA", "ERIN", "ESNA", "ISIS", "JADA", "JADE", "JANA", "JENE", "JINA", "LEIA", "LYNN", "MARY", "NINA", "SARA", "TEJA", "TONI", "TORI", "TYRA", "A'SJA", "AISSA", "ALINA", "AMARI", "AMIYA", "ANAYA", "ANGEL", "ANIAH", "ANIYA", "ARIEL", "ASHIA", "ATIRA", "AYANA", "CACHE", "CARLA", "CIARA", "CIARI", "CINDY", "DAIJA", "DEJAH", "DIEJA", "EBONY", "EMILY", "ERICA", "ERIKA", "JAMIA", "JANAE", "JANET", "JANYA", "JAVON", "JAYLA","JOANA", "KAJAH", "KAREN", "KAYLA", "KAYRA", "KENYA", "KEONA", "KEORA", "KEREN", "KIANA", "KIARA", "KYARA", "LEXIS", "LINDA", "LUARA", "MAIYA", "MAKYA", "MARIE", "MYKIA", "NADIA", "NAOMI", "NYLAH", "PARIS", "QUEEN", "RAVEN", "ROBYN", "SAIRA", "TAMIA", "TANIA", "TEHYA", "TIARA", "ULANI", "VICKY", "ZARIA"
    ]

  $female_short_unique = [
      "AJA", "TIA", "AMIA", "ASIA", "CIJI", "DAJA", "DEJA", "ERIN", "ESNA", "ISHA", "ISIS", "JADA", "JADE", "JAEL", "JAIA", "JANA", "JENE", "JINA", "LEIA", "LYNN", "NORA", "SADE", "TEJA", "A'SJA", "AMARI", "AMIYA", "ANAYA", "ANIAH", "ANIYA", "ASHER", "ASHIA", "ATIRA", "AYANA", "BETTY", "BRINE", "CACHE", "CIARA", "CIARI", "DAIJA", "DARLA", "DAZHA", "DEJAH", "DIEJA", "DIMOR", "DORIS", "EBONY", "EVITA", "GEIDY", "HEIDY", "INDYA", "IRENA", "J'NYA", "JAMIA", "JANET","JANYA", "JAVON", "JAYLA", "JENNY", "KAJAH", "KAYRA", "KELIS", "KENYA", "KEONA", "KEORA", "KEREN", "KIANA", "KIARA", "KYARA", "KYSIA", "LAUDZ", "LAURA", "LEANN", "LEXIS", "LINDA", "LUARA", "LYRIC", "MAIYA", "MAKYA", "MONAY", "MYKIA", "N'DIA", "NADIA", "NAOMI", "NAYAH", "NYLAH", "PARIS", "QUEEN", "RANDI", "SAIRA", "SANIA", "TAMIA", "TANIA", "TEHYA", "TERRI", "TIARA", "ULANI", "VASTY", "VICKY", "WINNY", "YOLNA", "ZARIA", "ZHANE", "ZOLAH"
    ]

  $female_short_outrageous = [
      "GIA", "LEY", "LUZ", "AKWE", "CIJI", "DORA", "ESNA", "ISHA", "JAEL", "LEIA", "SADE", "ASHER", "AYANA", "CACHE", "CIARI", "DIMOR", "EVITA", "HEIDY", "HILDA", "IBETH", "INDYA", "IRENA", "J'NYA", "JAYLA", "JENNY", "JOANA", "KAJAH", "KELIS", "KYSIA", "LAUDZ", "LEANN", "LYRIC", "MONAY", "N'DIA", "RANDI", "SANIA", "TADZA", "TEHYA", "TERRI", "VASTY", "WINNY", "YOLNA", "ZHANE", "ZOLAH"
    ]

  $female_short_meaningful = [
    "EVE", "ASIA", "ISIS", "MARY", "NINA", "A'SJA", "AISSA", "ALINA", "ANGEL", "AYANA", "KENYA", "N'DIA", "PARIS", "QUEEN", "ROBYN", "JO"
    ]

end