module ListOfUnisexNames
  $unisex_short = [
      "JO", "EVE", "GIA", "TIA", "AKWE", "AMIA", "CIJI", "ERIN", "JADE", "TONI", "TORI", "AMARI", "ANGEL", "ARIEL", "ASHER", "JAVON", "KELIS", "MARIE", "TERRI", "KEL", "ALEX", "ARON", "JANN", "REMY", "AARON", "AMANI", "AMATA", "ANGEL", "GABBY", "JAMIE", "MYKEL", "RAMON", "SHAWN", "TAKAI", "TRACY"
    ]

  $unisex_long = [
    "KIANTE", "WILSON", "CELESTE", "DESHAWN", "DESHUAN", "KEIEVIN", "KEMAURI", "MICHAEL", "MARQUELL", "DOMINIQUE", "DYMETRIUS", "ELIJEANNA", "HEROLDINE", "DEMETRIANN",     "ADRIAN", "ALBREE", "ASHLEY", "BJKLIS", "BREYON", "CAMRIN", "JESSIE", "KEONTE", "KEVION", "KIARYN", "MALAYA", "MAXINI", "MICHAH", "MIGUEL", "QUINCY", "CALIJAH", "GENESIS", "JAKAREE", "JUSTICE", "KENDLEY", "SHOMARI", "COURTNEY", "KIRNETTA"
      ]
end